### ISSUE TITLE
Installed JgeckoU on new pc. 

### ISSUE THREAD

**Issue by Leon7327** [BullyWiiPlaza/JGeckoU#101]
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at Wkb.m(rsg:321)
	at Yn.g(bfb:6283)
	at Yn.m(bfb:249)
	at bl.m(bfb:6477)
	at bl.doInBackground(bfb:6206)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

(anti virus and firewall was turned off btw and I tried other programs that use TCPGecko and they all have a similar issue)

**Comment by BullyWiiPlaza** [comment]
Since you said this issue happens with other programs too, it's clearly a problem on your PC, not the software itself. The error message says `permission denied` so make sure you allow `TCP` or socket connections on your PC, and specifically for `java.exe` by e.g. using an administrator account.

You can also try running `JGecko U` with the following command from `CMD`:
`java -Djava.net.preferIPv4Stack=true -jar "JGecko U.jar"`
For this you need to open `CMD` in the same folder as `JGecko U.jar` or change directory (`cd` command) into the right folder after opening `CMD`.
