### ISSUE TITLE
JAR crashing on open

### ISSUE THREAD

**Issue by QuarkTheAwesome** [BullyWiiPlaza/JGeckoU#17]
Heya!

I've been trying to get the latest JGeckoU master running on my Arch machine to fiddle around with Virtual Console titles. However, when I try and run it I always get one of two exceptions.

``` java
//openjdk version "1.8.0_102"
//OpenJDK Runtime Environment (build 1.8.0_102-b14)
//OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
//Not sure what's going on with the quotes

Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For inpu" string: "10015000
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:589)
    at java.lang.Integer.parseUnsignedInt(Integer.java:679)
    at wiiudev.gecko.client.codes.CodeListInformationReader.<init>(CodeListInformationReader.java:22)
    at wiiudev.gecko.client.codes.CodeListSender.<init>(CodeListSender.java:24)
    at wiiudev.gecko.client.gui.JGeckoUGUI.configureCodesTab(JGeckoUGUI.java:2542)
    at wiiudev.gecko.client.gui.JGeckoUGUI.<init>(JGeckoUGUI.java:228)
    at wiiudev.gecko.client.gui.JGeckoUGUI.getInstance(JGeckoUGUI.java:2268)
    at ApplicationGUILauncher.lambda$main$0(ApplicationGUILauncher.java:22)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

``` java
//java version "1.7.0_111"
//OpenJDK Runtime Environment (IcedTea 2.6.7) (Arch Linux build 7.u111_2.6.7-1-x86_64)
//OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

Exception in thread "main" java.lang.UnsupportedClassVersionError: ApplicationGUILauncher : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

Hope you can help me out with this. It's been a while since I used Java so I might be a bit out of my depth here ;D

**Comment by BullyWiiPlaza** [comment]
Yeah, the first one looks like a bug but it's not happening on Windows. It fails on parsing the addresses from the text file:
```
Code List Starting Address = 10015000
Code List End Address = 10017000
Code Handler Enabled Address = 10014CFC
```

The 2nd one means your Java is outdated and you have to update it to `Java 8`.

**Comment by CreeperMario** [comment]
I don't think OpenJDK Java is the same as Oracle Java. Hence why @QuarkTheAwesome is receiving version mismatch errors.

The file parsing error might be due to the program looking for CRLF (Windows) line endings, even though UNIX-based platforms use LF line endings. I might be wrong, its been a while since I last used Java as well. ;)

**Comment by BullyWiiPlaza** [comment]
The line separators are correct though:
```
String codeListInformation = ClasspathUtilities.getClassPathString("Code List.txt");
String[] codeListInformationLines = codeListInformation.split(System.lineSeparator());
```

Since I updated and it worked on `Kali`, it might be fixed for him, too.
