### ISSUE TITLE
Error message when doing a second search for a specific value

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#22]
So I was trying to recreate my powerup modifier that I did for Super Mario 3D World, and I get an error when trying to do **a 32bit specific search for the second time**. Trying to press the search button results in the same error appearing. 

I also did some testing in Splatoon and was able to get the error message to appear with doing a **16bit and 8bit search for the second time**.
```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at wiiudev.gecko.client.tcpgecko.main.TCPGecko.readStatus(TCPGecko.java:42)
	at wiiudev.gecko.client.tcpgecko.main.MemoryReader.readBytes(MemoryReader.java:273)
	at wiiudev.gecko.client.tcpgecko.main.MemoryReader.readBytes(MemoryReader.java:242)
	at wiiudev.gecko.client.memory_search.SearchQueryOptimizer$MemoryDumpingChunk.dump(SearchQueryOptimizer.java:153)
	at wiiudev.gecko.client.gui.tabs.memory_search.GraphicalRefiner$MemoryDumpingTask.doInBackground(GraphicalRefiner.java:57)
	at wiiudev.gecko.client.gui.tabs.memory_search.GraphicalRefiner$MemoryDumpingTask.doInBackground(GraphicalRefiner.java:43)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Dec 13, 2016 9:44:52 PM wiiudev.gecko.client.debugging.ErrorLogger log
SEVERE: 
java.lang.NullPointerException
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:396)
	at wiiudev.gecko.client.memory_search.SearchQueryOptimizer.dumpBytes(SearchQueryOptimizer.java:104)
	at wiiudev.gecko.client.memory_search.MemorySearcher.search(MemorySearcher.java:56)
	at wiiudev.gecko.client.gui.JGeckoUGUI$5.doInBackground(JGeckoUGUI.java:621)
	at wiiudev.gecko.client.gui.JGeckoUGUI$5.doInBackground(JGeckoUGUI.java:604)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Not sure if I am doing something wrong. I download these softwares:
JGecko: https://github.com/BullyWiiPlaza/JGeckoU/commit/5d29656602736f099db1d6733360206a71af9762
TCPGecko: https://github.com/BullyWiiPlaza/tcpgecko/commit/8b44e541401ffc15df3e2516bb4c2d646940981c

And I know I am using the correct version of TCPGecko since I did not get the error that appears when using the wrong version.

**Comment by BullyWiiPlaza** [comment]
Weird. What if you reconnect after the first search? Will it happen? 

Either way, I'm updating the dumping memory code for the TCP Gecko Installer now so things might change. I'm trying to make it faster again since it's really important.

**Comment by CuriousTommy** [comment]
> Weird. What if you reconnect after the first search? Will it happen?

I tested two times with Super Mario 3D World and I still have the same error message.

**Comment by CuriousTommy** [comment]
Apparently the issue seems to be fixed, I can at least do a 32bit specific search in Super Mario 3D World. Thanks Bully! I will reopen this if I still experience issues with doing specific searches.
