### ISSUE TITLE
Can't send codes.

### ISSUE THREAD

**Issue by TalkerMan39** [BullyWiiPlaza/JGeckoU#48]
So, I've updated the JGeckoU recently and I've run across this. Before you ask, yes, I have all of the files I need, but when I try to connect this pops up first:

Dec 14, 2017 8:13:57 PM wiiudev.gecko.client.Pb d
SEVERE: 
java.lang.NullPointerException
    at wiiudev.gecko.client.XE.d(Unknown Source)
    at wiiudev.gecko.client.XE.Y(Unknown Source)
    at wiiudev.gecko.client.XE.d(Unknown Source)
    at wiiudev.gecko.client.XE.d(Unknown Source)
    at wiiudev.gecko.client.uf.d(Unknown Source)
    at wiiudev.gecko.client.uf.doInBackground(Unknown Source)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

And then when I try to send codes, I get this:

![](https://i.imgur.com/crXnYVy.png)

Everything else seems to be working as if JGecko was connected to the Wii U.

**Comment by BullyWiiPlaza** [comment]
I fixed it but could you explain to me how you didn't figure out how to get around this?

If you start program, it will download the `Titles.xml` and if you connect before that happens it will run into exactly this error. Both problems are caused by this. However, at the second connection attempt the download would certainly be finished so it would work fine. Also all subsequent starts of the program would no longer have to deal with the download process since the file is already there. Can you explain to me how your Internet didn't manage the ~ 443KB in any reasonable time and did you even have Internet access the whole time? Only special kinds of users would be stuck on a minor issue like this lol.
