### ISSUE TITLE
Guide on raw machine codes?

### ISSUE THREAD

**Issue by TheNeutral-i** [BullyWiiPlaza/JGeckoU#56]
Please release a guide on how to use Raw Machine codes, because they still aren't working, even in the newest builds. I believe you fixed the problem, so maybe it's something me and the others are doing wrong, but either way it would help to know how to use these types of codes in the future.

Thank you!

**Comment by BullyWiiPlaza** [comment]
You need to know PowerPC assembly to write them. Each instruction is 1 block in the code. No code types and nothing else. `blr` is added at the end automatically so it won't crash.

**Comment by TheNeutral-i** [comment]
Ah apologies, what I meant was how to actually send the codes in gameplay. Whenever I try to send any Raw Machine code it always throws me an error. No Raw Machine code works.

**Comment by BullyWiiPlaza** [comment]
Please post the exact error message and all related lines from the log files here.

**Comment by TheNeutral-i** [comment]
Here's the error
![image](https://user-images.githubusercontent.com/38018984/44559346-7d1dee00-a717-11e8-98b0-bb2a0ecfdc74.png)
The code used here that set it off was "Stalker Part 2" by Darkflare (it's the exact same part 2 code, just with a shortened name). I'm sure you know what the code looks like by now, but I can repost it if you want.

The thing about this, though, is that _any_ Raw Machine code throws this error, not just Darkflare's stuff. In fact, if you uncheck the "Raw Machine Code" box, the code _will_ send, but (obviously) won't _work_.

A lot of users have been having this issue lately, and it's hard to tell why. For reference, I have the latest version of JGeckoU and TCPGecko and nothing else. Am I missing an essential plugin for this to work?

**Comment by BullyWiiPlaza** [comment]
Please post the error **in text format** like how it is written in the log files, not a picture.

**Comment by TheNeutral-i** [comment]
Sorry my man. I didn't quite understand you at first. Here you go:

Aug 24, 2018 1:47:40 AM Nd j
SEVERE: 
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.DataOutputStream.flush(Unknown Source)
	at Me.j(Unknown Source)
	at Me.j(Unknown Source)
	at Me.j(Unknown Source)
	at II.j(Unknown Source)
	at II.j(Unknown Source)
	at II.K(Unknown Source)
	at II.j(Unknown Source)
	at oI.DB(Unknown Source)
	at oI.va(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by BullyWiiPlaza** [comment]
This is the wrong one, please post the one from the image. Thanks.

**Comment by TheNeutral-i** [comment]
Alright this is the one.

Aug 23, 2018 8:48:33 PM Nd j
SEVERE: 
java.lang.NullPointerException
	at Oi.j(Unknown Source)
	at Me.j(Unknown Source)
	at Me.j(Unknown Source)
	at Me.J(Unknown Source)
	at II.K(Unknown Source)
	at II.K(Unknown Source)
	at II.J(Unknown Source)
	at oI.d(Unknown Source)
	at oI.Sa(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by TheNeutral-i** [comment]
Apologies for being so bad at this, but I'm doing my best.

**Comment by BullyWiiPlaza** [comment]
I tested it once again and it works perfectly. I'm making a video tutorial now so make sure to follow it step-by-step to see that it works. This is the last time I will react to this kind of thing because I'm tired of this nonsense user idiocy: https://www.youtube.com/watch?v=2uLOTrAc7zc
