### ISSUE TITLE
Unreadable text and access denied message

### ISSUE THREAD

**Issue by LegitDax009** [BullyWiiPlaza/JGeckoU#58]
![image](https://user-images.githubusercontent.com/38143460/45930555-465e1200-bf27-11e8-8a0c-e093eab5794c.png)
Here's the error (I know it's an access denied message because the same message was on a mac

**Comment by BullyWiiPlaza** [comment]
It's the font settings on your computer.
Just leave the defaults and don't configure some weird font like this.
I can't help with the error since it's unreadable for me so please get me the error in a regular font or text format. The logs directory exists for a reason.

Thanks!

**Comment by LegitDax009** [comment]
Here's what the logs say:

Sep 23, 2018 11:53:07 AM PB G
SEVERE: 
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=http://wiiubrew.org/wiki/Cafe_OS_Syscalls
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:776)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295)
	at MD.G(ql:119)
	at li.RC(pw:13753)
	at java.lang.Thread.run(Unknown Source)

Sep 23, 2018 11:53:09 AM PB G
SEVERE: 
java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at cd.G(nj:237)
	at cd.d(nj:117)
	at cd.G(nj:362)
	at cd.G(nj:299)
	at oB.G(mj:254)
	at oB.<init>(mj:34)
	at li.mB(pw:20893)
	at java.lang.Thread.run(Unknown Source)

**Comment by BullyWiiPlaza** [comment]
Thanks, both issues were known already. They will be fixed soon.

**Comment by GeorgeGamingYT** [comment]
Hi bullyWiiPLaza I am George And i had the same issue with Jgecko U everytime i'd load it i would be welcome with a text saying
ep 23, 2018 2:12:51 PM PB G
SEVERE: 
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=http://wiiubrew.org/wiki/Cafe_OS_Syscalls
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:776)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295)
	at MD.G(ql:119)
	at li.RC(pw:13753)
	at java.lang.Thread.run(Unknown Source)

Sep 23, 2018 2:12:52 PM PB G
SEVERE: 
java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at cd.G(nj:237)
	at cd.d(nj:117)
	at cd.G(nj:362)
	at cd.G(nj:299)
	at oB.G(mj:254)
	at oB.<init>(mj:34)
	at li.mB(pw:20893)
	at java.lang.Thread.run(Unknown Source)

This would happen everytime i load it and it errase my data but it will leave my ip which i can't connect to because the connect button is grey and i can't click on it or send codes.. this has been going on since sunday but then i was only able to connect to my Wii u once but it crashed my wii u up to then jgecko has never worked then giving me error's :[
