### ISSUE TITLE
When trying to retrieve the threads, it stays stuck at "Retrieving..."

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#6]
When the press the retrieve threads button, it says stuck on Retrieving... It has been like this for 1 hour and 40 minutes. There aren't any error messages that are shown on the console window.

I am running the latest version of your software. I am also using the latest version of TCPGecko.elf
Operating System (PC): Arch Linux (updated this morning)
Wii U Firmware: 5.3.2U (Spoofed)
Game: Super Mario 3D World (NTSC-U)

**Comment by amibu01** [comment]
Restart your console and JGecko, then try again. It seems to be rather unstable, took me a few tries each time, but if it works they should appear pretty quickly (3-4 seconds).

**Comment by BullyWiiPlaza** [comment]
Yes, it's still unstable but works most of the time. I will see if I can fix it.

**Comment by CuriousTommy** [comment]
@amibu01 Yeah, I will give it a try and see if I can successfully get the threads shown.

**Comment by BullyWiiPlaza** [comment]
@amibu01 It's enough to restart JGecko U because it froze itself and not the Wii U. It's still an unresolved issue

**Comment by amibu01** [comment]
I had quite a few handler crashes too - that's why I said restart your console, just in case. "Handler crash" as in "requests are failing and the WiiU crashes when trying to open the home menu".

**Comment by CuriousTommy** [comment]
@amibu01 Have you sometimes experience crashes where the console makes a long beep noise before it stops when retrieving the thread? Is that normal?

**Comment by amibu01** [comment]
That's a full crash of the a game thread or a critical system thread, means something went wrong. You sadly can't do much about that other than retrying.

**Comment by BullyWiiPlaza** [comment]
Is this issue resolved? Please let me know :)

**Comment by CuriousTommy** [comment]
Yeah, it still happens. The only difference is that I am actually on 5.5.1 this time. I am going to test on another game and see if I have the same issue.

**Comment by CuriousTommy** [comment]
Okay, do I did some more testing. I tested with Mario Kart 8 and Super Smash Bro U (both are US version). I was only able to successfully retrieve the thread once from Super Smash Bro U but after that, it stays stuck on `Retrieving...` 

However, I noticed that occasionally I get the Socket closed error, but I don't know if it is actually related to the issue. I only encounter that error when I try to retrieve the thread. 

```
[user@computername WiiU Software]$ java -jar JGecko\ U.jar
Aug 21, 2016 10:56:09 AM wiiudev.gecko.client.debugging.ErrorLogger log
SEVERE: 
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at wiiudev.gecko.client.tcpgecko.main.TCPGecko.readStatus(TCPGecko.java:45)
	at wiiudev.gecko.client.tcpgecko.main.MemoryReader.readBytes(MemoryReader.java:374)
	at wiiudev.gecko.client.tcpgecko.main.MemoryReader.readBytes(MemoryReader.java:337)
	at wiiudev.gecko.client.tcpgecko.main.MemoryReader.readInt(MemoryReader.java:69)
	at wiiudev.gecko.client.tcpgecko.main.threads.OSThread.setInternalState(OSThread.java:95)
	at wiiudev.gecko.client.tcpgecko.main.threads.OSThread.setFields(OSThread.java:90)
	at wiiudev.gecko.client.tcpgecko.main.threads.OSThread.<init>(OSThread.java:27)
	at wiiudev.gecko.client.tcpgecko.main.threads.OSThread.readThreads(OSThread.java:46)
	at wiiudev.gecko.client.gui.tabs.threads.ThreadsTableManager.updateRows(ThreadsTableManager.java:110)
	at wiiudev.gecko.client.gui.JGeckoUGUI$10.doInBackground(JGeckoUGUI.java:828)
	at wiiudev.gecko.client.gui.JGeckoUGUI$10.doInBackground(JGeckoUGUI.java:817)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by BullyWiiPlaza** [comment]
The socket closed error has been fixed though

**Comment by CuriousTommy** [comment]
Maybe I should ask someone else who has a US Wii U to test the retrieving thread feature.

**Comment by CuriousTommy** [comment]
Okay, so I talked to the TheWord21 on Gbatemp and he is also having issues too. He has US Wii U, however, he is using Windows instead. He tested five times with no results.
