### ISSUE TITLE
Searching for a Unknown results in a "BufferUnderflowException"

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#9]
The error also happens when selecting `Specific` in the Search Condition section. It does not seem to happen when I select `8-Bit`, but does when I select `16-Bit`, `32-Bit`, or `64-Bit`.

This is the terminal output:
```
[user@computername WiiU Software]$ java -jar JGecko\ U.jar

Aug 20, 2016 10:20:46 AM wiiudev.gecko.client.debugging.ErrorLogger log
SEVERE: 
java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at wiiudev.gecko.client.search.MemorySearcher.getValue(MemorySearcher.java:172)
	at wiiudev.gecko.client.search.MemorySearcher.search(MemorySearcher.java:49)
	at wiiudev.gecko.client.gui.JGeckoUGUI$4.doInBackground(JGeckoUGUI.java:402)
	at wiiudev.gecko.client.gui.JGeckoUGUI$4.doInBackground(JGeckoUGUI.java:380)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Here is a screenshot also:
![image](https://cloud.githubusercontent.com/assets/3105794/17832760/5836b3c8-66bf-11e6-8669-f8e13f00f63a.png)

**Comment by BullyWiiPlaza** [comment]
Fixed :+1:
