### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by Greyaaaa** [BullyWiiPlaza/JGeckoU#94]
So, I like modding Minecraft Wii U, and my thing keeps crashing every time I try to load the JGECKO U or connect it. My WII U crashes and gives me an error code. I don't know what to do.
 
I keep on having to use mod injectors, There is another error. I use Haxchi, and I load mocha each time. I press X, the right button. I don't know what's wrong??

java.lang.IllegalStateException: Wii U with working TCP Gecko server not found
	at ZP.Ea(cab:3574)
	at ZP.f(cab:148)
	at Zn.H(cab:4771)
	at Zn.doInBackground(cab:7108)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I accidentally took a screenshot.
And another error?

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at fWb.M(zqh:637)
	at fWb.F(zqh:480)
	at ZP.v(cab:5159)
	at ZP.a(cab:148)
	at Zn.H(cab:4206)
	at Zn.doInBackground(cab:7108)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I don't know what's wrong??

If you could help, that would be very appreciated!

Another one!

java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.DataOutputStream.flush(Unknown Source)
	at fWb.F(zqh:863)
	at ZP.M(cab:1111)
	at java.lang.Thread.run(Unknown Source)
I need serious help! I know I'm doing something wrong here!!

**Comment by BullyWiiPlaza** [comment]
First, this error:
```java.lang.IllegalStateException: Wii U with working TCP Gecko server not found```
It means you were using the auto detect feature and it didn't find your Wii U in the network. If it is in the network and you know the IP you should enter it directly and not use the auto detect checkbox for speed benefits.

The other 2 errors mean the connection was killed and that writing to the Wii U failed, most likely because it crashed or because you switched Wii U titles etc.
I need more information on what you did when it crashed so I can try to reproduce it. Currently I never have connection problems. Did you make sure you're using the "Memory Address Protection" option?

**Comment by Greyaaaa** [comment]
Um, no I didn't. I don't know where the memory adress protection option is.

**Comment by Greyaaaa** [comment]
Ok, so please reply? Its been days lol.

So i went to haxchi, and held the a button till i got to the homebrew launcher. I loaded mocha with no fs hax. I waited and i returned to the home brew menu. Then i went to the tcp gecko and pressed x. I went to the wii u menu and i opened minecraft. I joined my friends world and i typed my ip in jgecko u and connected. Then my wii u screen went glitched and i had to reset it. It will not stop doing this. 

1. I had to reset my pc. Factory reset, so i lost all my codes and settings.

2. I know im doing everything right but theres something fishy going on.

**Comment by BullyWiiPlaza** [comment]
I'm not sure what's wrong, maybe you are not using the right TCP Gecko Installer?
https://github.com/BullyWiiPlaza/tcpgecko/blob/master/tcpgecko.elf?raw=true

**Comment by Greyaaaa** [comment]
OK, im testing that now! hopefully it works! ill sent another post if it works or not.

**Comment by Greyaaaa** [comment]
Nope. Failed AGAIN. I have to be doing something wrong lmfao

**Comment by Greyaaaa** [comment]
Status....

**Comment by BullyWiiPlaza** [comment]
None because you need to just follow the setup guide. If it was really broken, nobody else could use it either. I'm sorry but I don't know what else to suggest. You can also join the Discord and ask other people:
https://discord.gg/XVA6SjJyC8

**Comment by Greyaaaa** [comment]
Ok, wheres the setup guide tho??
I might wanna read it again..
