### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by ByQuartz** [BullyWiiPlaza/JGeckoU#97]
When i press connect with the right IP Adress This shows up

java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.DataOutputStream.flush(Unknown Source)
	at fWb.F(zqh:863)
	at ZP.M(cab:1111)
	at java.lang.Thread.run(Unknown Source)

**Comment by ByQuartz** [comment]
never mind my pc was just using an old java my bad

**Comment by ByQuartz** [comment]
never mind my pc was just using an old java my bad
