### ISSUE TITLE
A big mistake

### ISSUE THREAD

**Issue by Thegamerdu2102** [BullyWiiPlaza/JGeckoU#99]
Hi,
While using your software to operate Splatoon 1 on Nintendo wiiu I encountered this error and it crashed my console at the same time

If you could tell me how to solve this problem I would appreciate it

**java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.DataOutputStream.flush(Unknown Source)
	at Tmb.F(tug:618)
	at Tmb.e(tug:608)
	at mO.U(geb:3033)
	at mO.C(geb:189)
	at PK.m(geb:2949)
	at PK.doInBackground(geb:6958)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)**

Sorry I am using a translator

**Comment by BullyWiiPlaza** [comment]
This is a normal crash error message, there are no other information provided. You need to make sure whatever you did isn't breaking anything in-game such as the codes you were running.

**Comment by Thegamerdu2102** [comment]
When I pressed the connect button my wiiu displayed a black screen with error codes

After restarting my console and Splatoon all are working normally

**Comment by Thegamerdu2102** [comment]
![Uploading IMG_20210126_151505.jpg…]()

**Comment by Thegamerdu2102** [comment]
Here's the crash 

https://drive.google.com/file/d/1L3_pa-7WxsziqshZ_Op9U6YoxdrhPur4/view?usp=drivesdk
